Adding add blog and comment section
Surajbokde/Nature_Beauty pull request #57
Opened 2020-12-25 11:12 UTC by Kerveyfelix

Fixes: #56 

![image](https://user-images.githubusercontent.com/46436993/103133375-1d152900-46d0-11eb-8b9f-d0c59d1b3b14.png)
![image](https://user-images.githubusercontent.com/46436993/103133390-2d2d0880-46d0-11eb-8a34-db4ba85d0b5d.png)

Kindly review my PR

2020-12-27 04:25 UTC, Surajbokde requested changes
@Kerveyfelix  do add write a blog field
i want name ,email ,title, blog field

2020-12-27 07:09 UTC, KerinPithawala commented
@Surajbokde  what should be the maximum blog length for text area?

2020-12-27 09:07 UTC, KerinPithawala commented
@Surajbokde I added the blog post area 
![image](https://user-images.githubusercontent.com/46436993/103167418-0ba75a80-4851-11eb-98f2-2e15b0aef9b0.png)

2020-12-28 04:41 UTC, Surajbokde approved these changes

2020-12-28 04:42 UTC, merged